ALTER TABLE wallets ADD COLUMN version BIGINT NOT NULL DEFAULT 0;
ALTER TABLE transactions ADD COLUMN version BIGINT NOT NULL DEFAULT 0;
ALTER TABLE projections ADD COLUMN version BIGINT NOT NULL DEFAULT 0;
